-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 20:38:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flight-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flight-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flight-db` DEFAULT CHARACTER SET utf8 ;
USE `flight-db` ;

-- -----------------------------------------------------
-- Table `flight-db`.`flgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight-db`.`flgt` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FLGT_NB` VARCHAR(50) NOT NULL,
  `APLN_TP` VARCHAR(100) NULL DEFAULT NULL,
  `DPRT_CT` VARCHAR(100) NULL DEFAULT NULL,
  `ARR_TM` VARCHAR(300) NULL,
  `NB_ST` INT(11) NULL DEFAULT NULL,
  `st_nb` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `FLGT_NB_UNIQUE` (`FLGT_NB` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 144
DEFAULT CHARACTER SET = utf8
COMMENT = 'APLN_TP 		-  airplane type\nDPRT_TM 	- departure time\nARR_TM		-arrival time\nUSR_ID		-foreign key to usr\nNB_ST		-number of seats available\nST_NB		-seat number for client';


-- -----------------------------------------------------
-- Table `flight-db`.`ct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight-db`.`ct` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `LAT` VARCHAR(100) NULL DEFAULT NULL,
  `LNGT` VARCHAR(100) NULL DEFAULT NULL,
  `NM` VARCHAR(100) NULL DEFAULT NULL,
  `FLGT_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ct_flgt_idx` (`FLGT_ID` ASC),
  CONSTRAINT `fk_ct_flgt`
    FOREIGN KEY (`FLGT_ID`)
    REFERENCES `flight-db`.`flgt` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flight-db`.`usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight-db`.`usr` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `F_NM` VARCHAR(45) NULL DEFAULT NULL,
  `L_NM` VARCHAR(45) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `ADDR` VARCHAR(100) NULL DEFAULT NULL,
  `TEL` VARCHAR(15) NULL DEFAULT NULL,
  `SER_ID` VARCHAR(20) NULL DEFAULT NULL,
  `ADM` TINYINT(4) NOT NULL,
  `PSWD` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `flight-db`.`usr_flgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flight-db`.`usr_flgt` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USR_ID` INT(11) NOT NULL,
  `FLGT_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_usr_usr_flgt_idx` (`USR_ID` ASC),
  INDEX `fk_flgt_usr_flgt_idx` (`FLGT_ID` ASC),
  CONSTRAINT `fk_flgt_usr_flgt`
    FOREIGN KEY (`FLGT_ID`)
    REFERENCES `flight-db`.`flgt` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usr_usr_flgt`
    FOREIGN KEY (`USR_ID`)
    REFERENCES `flight-db`.`usr` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
